import Head from "next/head";
import SearchBar from "@/components/SearchBar";
import { useSearch } from "@/store/search";

export default function Home() {
  const { results } = useSearch();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg flex h-screen flex-col items-center justify-center pt-header">
        <h1 className="mb-20 text-7xl font-extrabold tracking-tight sm:text-[5rem]">
          Elastic<span className="text-indigo-500">T3</span>Wiki
        </h1>

        <section className="flex w-10/12 max-w-sm flex-col items-center gap-6 sm:max-w-[36rem]">
          <SearchBar />
        </section>

        {results?.hits.hits.map((document) => {
          return <h1 key={document._id}>{document._source?.content}</h1>;
        })}
      </main>
    </>
  );
}
