import Head from "next/head";
import { api } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { useThemeStore } from "@/store/theme";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const { toggleTheme } = useThemeStore();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg flex min-h-screen flex-col items-center justify-center">
        <h1>teste</h1>
        <Button onClick={toggleTheme}>Primary</Button>
        <Button variant="secondary">Secondary</Button>
        <Button variant="ghost">Secondary</Button>
      </main>
    </>
  );
}
